export const caregiverProfileFieldPaths = [
  "full_name",
  "date_of_birth",
  "nationality",
  "id_number",
  "phone",
  "email",
  "address",
  "certifications",
  "medical_clearance.status",
  "medical_clearance.issue_date",
  "medical_clearance.expiry_date",
  "vaccinations",
  "languages",
  "years_experience",
  "emergency_contact.name",
  "emergency_contact.phone",
  "emergency_contact.relationship",
]

export const caregiverExtractionResultJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: ["caregiver_profile", "field_reviews", "document_results", "validation_issues"],
  properties: {
    caregiver_profile: {
      type: "object",
      additionalProperties: false,
      required: [
        "full_name",
        "date_of_birth",
        "nationality",
        "id_number",
        "phone",
        "email",
        "address",
        "certifications",
        "medical_clearance",
        "vaccinations",
        "languages",
        "years_experience",
        "emergency_contact",
      ],
      properties: {
        full_name: { type: ["string", "null"] },
        date_of_birth: { type: ["string", "null"] },
        nationality: { type: ["string", "null"] },
        id_number: { type: ["string", "null"] },
        phone: { type: ["string", "null"] },
        email: { type: ["string", "null"] },
        address: { type: ["string", "null"] },
        certifications: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["name", "number", "issue_date", "expiry_date"],
            properties: {
              name: { type: ["string", "null"] },
              number: { type: ["string", "null"] },
              issue_date: { type: ["string", "null"] },
              expiry_date: { type: ["string", "null"] },
            },
          },
        },
        medical_clearance: {
          type: "object",
          additionalProperties: false,
          required: ["status", "issue_date", "expiry_date"],
          properties: {
            status: { type: ["string", "null"] },
            issue_date: { type: ["string", "null"] },
            expiry_date: { type: ["string", "null"] },
          },
        },
        vaccinations: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["name", "date"],
            properties: {
              name: { type: ["string", "null"] },
              date: { type: ["string", "null"] },
            },
          },
        },
        languages: { type: "array", items: { type: "string" } },
        years_experience: { type: ["number", "null"] },
        emergency_contact: {
          type: "object",
          additionalProperties: false,
          required: ["name", "phone", "relationship"],
          properties: {
            name: { type: ["string", "null"] },
            phone: { type: ["string", "null"] },
            relationship: { type: ["string", "null"] },
          },
        },
      },
    },
    field_reviews: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "field_path",
          "value",
          "confidence",
          "confidence_band",
          "evidence",
          "issues",
          "requires_confirmation",
          "reviewed",
          "source_mode",
        ],
        properties: {
          field_path: { type: "string", enum: caregiverProfileFieldPaths },
          value: true,
          confidence: { type: "number", minimum: 0, maximum: 1 },
          confidence_band: { type: "string", enum: ["high", "medium", "low"] },
          evidence: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              required: ["snippet", "document_id", "page"],
              properties: {
                snippet: { type: "string" },
                document_id: { type: "string" },
                page: { type: ["number", "null"] },
              },
            },
          },
          issues: { type: "array", items: { type: "string" } },
          requires_confirmation: { type: "boolean" },
          reviewed: { type: "boolean" },
          source_mode: { type: "string", enum: ["manual", "autofill", "hybrid"] },
        },
      },
    },
    document_results: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "document_id",
          "file_name",
          "document_kind",
          "mime_type",
          "extraction_method",
          "raw_text",
          "raw_text_char_count",
        ],
        properties: {
          document_id: { type: "string" },
          file_name: { type: "string" },
          document_kind: { type: "string" },
          mime_type: { type: "string" },
          extraction_method: { type: "string" },
          raw_text: { type: "string" },
          raw_text_char_count: { type: "number" },
        },
      },
    },
    validation_issues: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["field_path", "code", "message", "severity"],
        properties: {
          field_path: { type: "string" },
          code: { type: "string" },
          message: { type: "string" },
          severity: { type: "string", enum: ["error", "warning"] },
        },
      },
    },
  },
}
